### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by daixiansen** [kenshinji/yddict#34]
C:\Users\daixiansen\AppData\Roaming\npm\node_modules\yddict>yd hello
C:\Users\daixiansen\AppData\Roaming\npm\node_modules\yddict\index.js:12
let word = process.argv.slice(2).join(' ')
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by kenshinji** [comment]
@daixiansen 你nodejs什么版本的？

**Comment by daixiansen** [comment]
应该是版本低了的问题

**Comment by kenshinji** [comment]
那应该可以关掉这个issue了
